const types = {
  FAVORITES_REQUEST: 'FAVORITES_REQUEST',
  FAVORITES_SUCCESS: 'FAVORITES_SUCCESS',
  FAVORITES_FAILURE: 'FAVORITES_FAILURE',
  FAVORITE_ADD_REQUEST: 'FAVORITE_ADD_REQUEST',
  FAVORITE_ADD_SUCCESS: 'FAVORITE_ADD_SUCCESS',
  FAVORITE_ADD_FAILURE: 'FAVORITE_ADD_FAILURE',
  FAVORITE_REMOVE_REQUEST: 'FAVORITE_REMOVE_REQUEST',
  FAVORITE_REMOVE_SUCCESS: 'FAVORITE_REMOVE_SUCCESS',
  FAVORITE_REMOVE_FAILURE: 'FAVORITE_REMOVE_FAILURE',
};

export default types;