const types = {
  WEATHER_REQUEST: 'WEATHER_REQUEST',
  WEATHER_SUCCESS: 'WEATHER_SUCCESS',
  WEATHER_FAILURE: 'WEATHER_FAILURE',
  WEATHER_NAME_REQUEST: 'WEATHER_NAME_REQUEST',
  WEATHER_NAME_SUCCESS: 'WEATHER_NAME_SUCCESS',
  WEATHER_NAME_FAILURE: 'WEATHER_NAME_FAILURE',
};

export default types;