const types = {
  FAVOURITES_REQUEST: 'FAVOURITES_REQUEST',
  FAVOURITES_SUCCESS: 'FAVOURITES_SUCCESS',
  FAVOURITES_FAILURE: 'FAVOURITES_FAILURE',
  FAVOURITE_ADD_REQUEST: 'FAVOURITE_ADD_REQUEST',
  FAVOURITE_ADD_SUCCESS: 'FAVOURITE_ADD_SUCCESS',
  FAVOURITE_ADD_FAILURE: 'FAVOURITE_ADD_FAILURE',
  FAVOURITE_REMOVE_REQUEST: 'FAVOURITE_REMOVE_REQUEST',
  FAVOURITE_REMOVE_SUCCESS: 'FAVOURITE_REMOVE_SUCCESS',
  FAVOURITE_REMOVE_FAILURE: 'FAVOURITE_REMOVE_FAILURE',
};

export default types;