const types = {
  FAVOURITES_REQUEST: 'FAVOURITES_REQUEST',
  FAVOURITES_SUCCESS: 'FAVOURITES_SUCCESS',
  FAVOURITE_ADD_REQUEST: 'FAVOURITE_ADD_REQUEST',
  FAVOURITE_ADD_SUCCESS: 'FAVOURITE_ADD_SUCCESS',
  FAVOURITE_REMOVE_REQUEST: 'FAVOURITE_REMOVE_REQUEST',
  FAVOURITE_REMOVE_SUCCESS: 'FAVOURITE_REMOVE_SUCCESS',
};

export default types;