name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy
      run: |
        git config --global user.name ${{ secrets.USER_NAME }}
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git remote set-url origin https://${{ secrets.DEPLOY_ACCESS_TOKEN }}@github.com/${{ secrets.USER_NAME }}/ilyacherkasov.github.io
        yarn deploy